### ISSUE TITLE
Not the latest build

### ISSUE THREAD

**Issue by revoice1** [MiSTer-unstable-nightlies/Unstable_Folder_MiSTer#1]
There seems to be an issue where the latest build isn't always included in this json.

Right now there have been three PSX core builds today but this json db seems to contain the last build based on alphabetical order, from the hash, not necessarily the latest build. Not the end of the world, but worth mentioning :)

![image](https://user-images.githubusercontent.com/41972431/152206639-c900ae66-70ea-4ec8-8a7a-7172d1c79892.png)

The DB has dd9b, but 9f1f is actually the most current build

I took a quick look at some code but couldn't easily figure out where this json was being generated, so I opened an issue here. Sorry if that wasn't the best option.

Thanks for all the hard work!

**Comment by theypsilon** [comment]
Thanks for the heads up! New releases will have the hour too.
